// College Athletics Directory - School Data
// 120+ schools across all major associations

const SCHOOLS = [
  // ── NCAA Division I ──────────────────────────────────────────────────────
  { id: 1,  name: "University of Alabama",         state: "Alabama",        stateCode: "AL", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://rolltide.com" },
  { id: 2,  name: "Auburn University",             state: "Alabama",        stateCode: "AL", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://auburntigers.com" },
  { id: 3,  name: "University of Arizona",         state: "Arizona",        stateCode: "AZ", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://arizonawildcats.com" },
  { id: 4,  name: "Arizona State University",      state: "Arizona",        stateCode: "AZ", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://thesundevils.com" },
  { id: 5,  name: "University of Arkansas",        state: "Arkansas",       stateCode: "AR", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://arkansasrazorbacks.com" },
  { id: 6,  name: "UCLA",                          state: "California",     stateCode: "CA", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://uclabruins.com" },
  { id: 7,  name: "USC",                           state: "California",     stateCode: "CA", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://usctrojans.com" },
  { id: 8,  name: "University of Colorado",        state: "Colorado",       stateCode: "CO", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://cubuffs.com" },
  { id: 9,  name: "University of Florida",         state: "Florida",        stateCode: "FL", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://floridagators.com" },
  { id: 10, name: "Florida State University",      state: "Florida",        stateCode: "FL", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://seminoles.com" },
  { id: 11, name: "University of Georgia",         state: "Georgia",        stateCode: "GA", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://georgiadogs.com" },
  { id: 12, name: "Georgia Tech",                  state: "Georgia",        stateCode: "GA", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://ramblinwreck.com" },
  { id: 13, name: "University of Illinois",        state: "Illinois",       stateCode: "IL", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://fightingillini.com" },
  { id: 14, name: "Northwestern University",       state: "Illinois",       stateCode: "IL", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://nusports.com" },
  { id: 15, name: "Indiana University",            state: "Indiana",        stateCode: "IN", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://iuhoosiers.com" },
  { id: 16, name: "Purdue University",             state: "Indiana",        stateCode: "IN", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://purduesports.com" },
  { id: 17, name: "University of Iowa",            state: "Iowa",           stateCode: "IA", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://hawkeyesports.com" },
  { id: 18, name: "University of Kansas",          state: "Kansas",         stateCode: "KS", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://kuathletics.com" },
  { id: 19, name: "Kansas State University",       state: "Kansas",         stateCode: "KS", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://kstatesports.com" },
  { id: 20, name: "University of Kentucky",        state: "Kentucky",       stateCode: "KY", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://ukathletics.com" },
  { id: 21, name: "LSU",                           state: "Louisiana",      stateCode: "LA", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://lsusports.net" },
  { id: 22, name: "University of Maryland",        state: "Maryland",       stateCode: "MD", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://umterps.com" },
  { id: 23, name: "University of Michigan",        state: "Michigan",       stateCode: "MI", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://mgoblue.com" },
  { id: 24, name: "Michigan State University",     state: "Michigan",       stateCode: "MI", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://msuspartans.com" },
  { id: 25, name: "University of Minnesota",       state: "Minnesota",      stateCode: "MN", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://gophersports.com" },
  { id: 26, name: "University of Missouri",        state: "Missouri",       stateCode: "MO", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://mutigers.com" },
  { id: 27, name: "University of Nebraska",        state: "Nebraska",       stateCode: "NE", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://huskers.com" },
  { id: 28, name: "Duke University",               state: "North Carolina", stateCode: "NC", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://goduke.com" },
  { id: 29, name: "UNC Chapel Hill",               state: "North Carolina", stateCode: "NC", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://tarheels.com" },
  { id: 30, name: "NC State University",           state: "North Carolina", stateCode: "NC", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://gopack.com" },
  { id: 31, name: "Ohio State University",         state: "Ohio",           stateCode: "OH", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://ohiostatebuckeyes.com" },
  { id: 32, name: "University of Oklahoma",        state: "Oklahoma",       stateCode: "OK", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://soonersports.com" },
  { id: 33, name: "Oklahoma State University",     state: "Oklahoma",       stateCode: "OK", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://okstate.com" },
  { id: 34, name: "University of Oregon",          state: "Oregon",         stateCode: "OR", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://goducks.com" },
  { id: 35, name: "Oregon State University",       state: "Oregon",         stateCode: "OR", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://osubeavers.com" },
  { id: 36, name: "Penn State University",         state: "Pennsylvania",   stateCode: "PA", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://gopsusports.com" },
  { id: 37, name: "University of Tennessee",       state: "Tennessee",      stateCode: "TN", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://utsports.com" },
  { id: 38, name: "Vanderbilt University",         state: "Tennessee",      stateCode: "TN", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://vucommodores.com" },
  { id: 39, name: "University of Texas",           state: "Texas",          stateCode: "TX", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://texassports.com" },
  { id: 40, name: "Texas A&M University",          state: "Texas",          stateCode: "TX", association: "NCAA Division I",   conference: "Southeastern Conference",          url: "https://12thman.com" },
  { id: 41, name: "Baylor University",             state: "Texas",          stateCode: "TX", association: "NCAA Division I",   conference: "Big 12 Conference",                url: "https://baylorbears.com" },
  { id: 42, name: "University of Utah",            state: "Utah",           stateCode: "UT", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://utahutes.com" },
  { id: 43, name: "Virginia Tech",                 state: "Virginia",       stateCode: "VA", association: "NCAA Division I",   conference: "Atlantic Coast Conference",        url: "https://hokiesports.com" },
  { id: 44, name: "University of Washington",      state: "Washington",     stateCode: "WA", association: "NCAA Division I",   conference: "Pac-12 Conference",                url: "https://gohuskies.com" },
  { id: 45, name: "University of Wisconsin",       state: "Wisconsin",      stateCode: "WI", association: "NCAA Division I",   conference: "Big Ten Conference",               url: "https://uwbadgers.com" },

  // ── NCAA Division II ─────────────────────────────────────────────────────
  { id: 46, name: "Valdosta State University",     state: "Georgia",        stateCode: "GA", association: "NCAA Division II",  conference: "Gulf South Conference",            url: "https://vstateblazers.com" },
  { id: 47, name: "Delta State University",        state: "Mississippi",    stateCode: "MS", association: "NCAA Division II",  conference: "Gulf South Conference",            url: "https://athletics.deltastate.edu" },
  { id: 48, name: "West Texas A&M University",     state: "Texas",          stateCode: "TX", association: "NCAA Division II",  conference: "Lone Star Conference",             url: "https://wtambuffs.com" },
  { id: 49, name: "Tarleton State University",     state: "Texas",          stateCode: "TX", association: "NCAA Division II",  conference: "Lone Star Conference",             url: "https://tarletonsports.com" },
  { id: 50, name: "Texas A&M-Commerce",            state: "Texas",          stateCode: "TX", association: "NCAA Division II",  conference: "Lone Star Conference",             url: "https://tamucathletics.com" },
  { id: 51, name: "Central Missouri",              state: "Missouri",       stateCode: "MO", association: "NCAA Division II",  conference: "Mid-America Intercollegiate Athletics Association", url: "https://ucmathletics.com" },
  { id: 52, name: "Northwest Missouri State",      state: "Missouri",       stateCode: "MO", association: "NCAA Division II",  conference: "Mid-America Intercollegiate Athletics Association", url: "https://nwmbearcat.com" },
  { id: 53, name: "Pittsburg State University",    state: "Kansas",         stateCode: "KS", association: "NCAA Division II",  conference: "Mid-America Intercollegiate Athletics Association", url: "https://pittstateathletics.com" },
  { id: 54, name: "Washburn University",           state: "Kansas",         stateCode: "KS", association: "NCAA Division II",  conference: "Mid-America Intercollegiate Athletics Association", url: "https://washburnathletics.com" },
  { id: 55, name: "Minnesota State Mankato",       state: "Minnesota",      stateCode: "MN", association: "NCAA Division II",  conference: "Northern Sun Intercollegiate Conference", url: "https://msumavericks.com" },
  { id: 56, name: "Augustana University",          state: "South Dakota",   stateCode: "SD", association: "NCAA Division II",  conference: "Northern Sun Intercollegiate Conference", url: "https://augie.edu/athletics" },
  { id: 57, name: "University of Sioux Falls",     state: "South Dakota",   stateCode: "SD", association: "NCAA Division II",  conference: "Northern Sun Intercollegiate Conference", url: "https://usfcougars.com" },
  { id: 58, name: "Winona State University",       state: "Minnesota",      stateCode: "MN", association: "NCAA Division II",  conference: "Northern Sun Intercollegiate Conference", url: "https://winonastateathletics.com" },
  { id: 59, name: "Colorado Mesa University",      state: "Colorado",       stateCode: "CO", association: "NCAA Division II",  conference: "Rocky Mountain Athletic Conference", url: "https://cmumavericks.com" },
  { id: 60, name: "Colorado School of Mines",      state: "Colorado",       stateCode: "CO", association: "NCAA Division II",  conference: "Rocky Mountain Athletic Conference", url: "https://minesathletics.com" },
  { id: 61, name: "Western Colorado University",   state: "Colorado",       stateCode: "CO", association: "NCAA Division II",  conference: "Rocky Mountain Athletic Conference", url: "https://wcumountaineers.com" },
  { id: 62, name: "UC San Diego",                  state: "California",     stateCode: "CA", association: "NCAA Division II",  conference: "California Collegiate Athletic Association", url: "https://ucsdtritons.com" },
  { id: 63, name: "Cal Poly Pomona",               state: "California",     stateCode: "CA", association: "NCAA Division II",  conference: "California Collegiate Athletic Association", url: "https://athletics.cpp.edu" },
  { id: 64, name: "Fayetteville State University", state: "North Carolina", stateCode: "NC", association: "NCAA Division II",  conference: "Central Intercollegiate Athletic Association", url: "https://fsubroncos.com" },
  { id: 65, name: "Winston-Salem State University",state: "North Carolina", stateCode: "NC", association: "NCAA Division II",  conference: "Central Intercollegiate Athletic Association", url: "https://athletics.wssu.edu" },
  { id: 66, name: "Bowie State University",        state: "Maryland",       stateCode: "MD", association: "NCAA Division II",  conference: "Central Intercollegiate Athletic Association", url: "https://athletics.bowiestate.edu" },
  { id: 67, name: "Virginia State University",     state: "Virginia",       stateCode: "VA", association: "NCAA Division II",  conference: "Central Intercollegiate Athletic Association", url: "https://vstrojansnation.com" },

  // ── NCAA Division III ────────────────────────────────────────────────────
  { id: 68, name: "Williams College",              state: "Massachusetts",  stateCode: "MA", association: "NCAA Division III", conference: "New England Small College Athletic Conference", url: "https://athletics.williams.edu" },
  { id: 69, name: "Amherst College",               state: "Massachusetts",  stateCode: "MA", association: "NCAA Division III", conference: "New England Small College Athletic Conference", url: "https://athletics.amherst.edu" },
  { id: 70, name: "Tufts University",              state: "Massachusetts",  stateCode: "MA", association: "NCAA Division III", conference: "New England Small College Athletic Conference", url: "https://athletics.tufts.edu" },
  { id: 71, name: "Bowdoin College",               state: "Maine",          stateCode: "ME", association: "NCAA Division III", conference: "New England Small College Athletic Conference", url: "https://athletics.bowdoin.edu" },
  { id: 72, name: "Middlebury College",            state: "Vermont",        stateCode: "VT", association: "NCAA Division III", conference: "New England Small College Athletic Conference", url: "https://athletics.middlebury.edu" },
  { id: 73, name: "Swarthmore College",            state: "Pennsylvania",   stateCode: "PA", association: "NCAA Division III", conference: "Centennial Conference",            url: "https://athletics.swarthmore.edu" },
  { id: 74, name: "Dickinson College",             state: "Pennsylvania",   stateCode: "PA", association: "NCAA Division III", conference: "Centennial Conference",            url: "https://dickinsonsports.com" },
  { id: 75, name: "Gettysburg College",            state: "Pennsylvania",   stateCode: "PA", association: "NCAA Division III", conference: "Centennial Conference",            url: "https://gettysburgathletics.com" },
  { id: 76, name: "Johns Hopkins University",      state: "Maryland",       stateCode: "MD", association: "NCAA Division III", conference: "Centennial Conference",            url: "https://hopkinssports.com" },
  { id: 77, name: "Calvin University",             state: "Michigan",       stateCode: "MI", association: "NCAA Division III", conference: "Michigan Intercollegiate Athletic Association", url: "https://calvin.edu/athletics" },
  { id: 78, name: "Hope College",                  state: "Michigan",       stateCode: "MI", association: "NCAA Division III", conference: "Michigan Intercollegiate Athletic Association", url: "https://athletics.hope.edu" },
  { id: 79, name: "Kalamazoo College",             state: "Michigan",       stateCode: "MI", association: "NCAA Division III", conference: "Michigan Intercollegiate Athletic Association", url: "https://athletics.kzoo.edu" },
  { id: 80, name: "Grinnell College",              state: "Iowa",           stateCode: "IA", association: "NCAA Division III", conference: "Midwest Conference",               url: "https://pioneers.grinnell.edu" },
  { id: 81, name: "Lawrence University",           state: "Wisconsin",      stateCode: "WI", association: "NCAA Division III", conference: "Midwest Conference",               url: "https://lawrencevikings.com" },
  { id: 82, name: "Carleton College",              state: "Minnesota",      stateCode: "MN", association: "NCAA Division III", conference: "Minnesota Intercollegiate Athletic Conference", url: "https://athletics.carleton.edu" },
  { id: 83, name: "St. Olaf College",              state: "Minnesota",      stateCode: "MN", association: "NCAA Division III", conference: "Minnesota Intercollegiate Athletic Conference", url: "https://stolafathletics.com" },
  { id: 84, name: "Carnegie Mellon University",    state: "Pennsylvania",   stateCode: "PA", association: "NCAA Division III", conference: "University Athletic Association",  url: "https://athletics.cmu.edu" },
  { id: 85, name: "Emory University",              state: "Georgia",        stateCode: "GA", association: "NCAA Division III", conference: "University Athletic Association",  url: "https://emoryathletics.com" },
  { id: 86, name: "University of Rochester",       state: "New York",       stateCode: "NY", association: "NCAA Division III", conference: "University Athletic Association",  url: "https://rochesterathletics.com" },
  { id: 87, name: "Rensselaer Polytechnic Institute", state: "New York",    stateCode: "NY", association: "NCAA Division III", conference: "Liberty League",                  url: "https://rpiathletics.com" },
  { id: 88, name: "Union College",                 state: "New York",       stateCode: "NY", association: "NCAA Division III", conference: "Liberty League",                  url: "https://unionathletics.com" },
  { id: 89, name: "Vassar College",                state: "New York",       stateCode: "NY", association: "NCAA Division III", conference: "Liberty League",                  url: "https://vassarathletics.com" },

  // ── NAIA ─────────────────────────────────────────────────────────────────
  { id: 90, name: "Benedictine College",           state: "Kansas",         stateCode: "KS", association: "NAIA",              conference: "Heart of America Athletic Conference", url: "https://athletics.benedictine.edu" },
  { id: 91, name: "MidAmerica Nazarene University",state: "Kansas",         stateCode: "KS", association: "NAIA",              conference: "Heart of America Athletic Conference", url: "https://mnupioneerathletics.com" },
  { id: 92, name: "Ottawa University",             state: "Kansas",         stateCode: "KS", association: "NAIA",              conference: "Heart of America Athletic Conference", url: "https://ottawabraves.com" },
  { id: 93, name: "William Jewell College",        state: "Missouri",       stateCode: "MO", association: "NAIA",              conference: "Heart of America Athletic Conference", url: "https://jwathletics.com" },
  { id: 94, name: "Graceland University",          state: "Iowa",           stateCode: "IA", association: "NAIA",              conference: "Heart of America Athletic Conference", url: "https://graceland.edu/athletics" },
  { id: 95, name: "Indiana Wesleyan University",   state: "Indiana",        stateCode: "IN", association: "NAIA",              conference: "Crossroads League",                url: "https://iwuwildcats.com" },
  { id: 96, name: "Bethel University",             state: "Indiana",        stateCode: "IN", association: "NAIA",              conference: "Crossroads League",                url: "https://athletics.betheluniversity.edu" },
  { id: 97, name: "Taylor University",             state: "Indiana",        stateCode: "IN", association: "NAIA",              conference: "Crossroads League",                url: "https://taylor.edu/athletics" },
  { id: 98, name: "Marian University",             state: "Indiana",        stateCode: "IN", association: "NAIA",              conference: "Crossroads League",                url: "https://marianknights.com" },
  { id: 99, name: "Northwestern College",          state: "Iowa",           stateCode: "IA", association: "NAIA",              conference: "Great Plains Athletic Conference",  url: "https://nwcraiders.com" },
  { id: 100,name: "Morningside University",        state: "Iowa",           stateCode: "IA", association: "NAIA",              conference: "Great Plains Athletic Conference",  url: "https://morningsidemustangs.com" },
  { id: 101,name: "Dordt University",              state: "Iowa",           stateCode: "IA", association: "NAIA",              conference: "Great Plains Athletic Conference",  url: "https://defenders.dordt.edu" },
  { id: 102,name: "Concordia University Nebraska", state: "Nebraska",       stateCode: "NE", association: "NAIA",              conference: "Great Plains Athletic Conference",  url: "https://athletics.cune.edu" },
  { id: 103,name: "Hastings College",              state: "Nebraska",       stateCode: "NE", association: "NAIA",              conference: "Great Plains Athletic Conference",  url: "https://hastingsbroncos.com" },
  { id: 104,name: "College of Idaho",              state: "Idaho",          stateCode: "ID", association: "NAIA",              conference: "Frontier Conference",               url: "https://yotesports.com" },
  { id: 105,name: "Montana Tech",                  state: "Montana",        stateCode: "MT", association: "NAIA",              conference: "Frontier Conference",               url: "https://orediggers.com" },
  { id: 106,name: "Rocky Mountain College",        state: "Montana",        stateCode: "MT", association: "NAIA",              conference: "Frontier Conference",               url: "https://athletics.rocky.edu" },

  // ── NJCAA ────────────────────────────────────────────────────────────────
  { id: 107,name: "Hutchinson Community College",  state: "Kansas",         stateCode: "KS", association: "NJCAA",             conference: "Kansas Jayhawk Community College Conference", url: "https://hutchbluedragonathletics.com" },
  { id: 108,name: "Barton Community College",      state: "Kansas",         stateCode: "KS", association: "NJCAA",             conference: "Kansas Jayhawk Community College Conference", url: "https://bartoncc.edu/athletics" },
  { id: 109,name: "Coffeyville Community College", state: "Kansas",         stateCode: "KS", association: "NJCAA",             conference: "Kansas Jayhawk Community College Conference", url: "https://coffeyvcc.edu/athletics" },
  { id: 110,name: "Butler Community College",      state: "Kansas",         stateCode: "KS", association: "NJCAA",             conference: "Kansas Jayhawk Community College Conference", url: "https://butlergrizzlies.com" },
  { id: 111,name: "Iowa Central Community College",state: "Iowa",           stateCode: "IA", association: "NJCAA",             conference: "Iowa Community College Athletic Conference", url: "https://iowacentral.edu/athletics" },
  { id: 112,name: "Iowa Western Community College",state: "Iowa",           stateCode: "IA", association: "NJCAA",             conference: "Iowa Community College Athletic Conference", url: "https://iowawestern.edu/athletics" },
  { id: 113,name: "Des Moines Area Community College", state: "Iowa",       stateCode: "IA", association: "NJCAA",             conference: "Iowa Community College Athletic Conference", url: "https://dmacc.edu/athletics" },
  { id: 114,name: "College of DuPage",             state: "Illinois",       stateCode: "IL", association: "NJCAA",             conference: "Northern Illinois Junior College Athletic Conference", url: "https://cod.edu/athletics" },
  { id: 115,name: "Triton College",                state: "Illinois",       stateCode: "IL", association: "NJCAA",             conference: "Northern Illinois Junior College Athletic Conference", url: "https://triton.edu/athletics" },
  { id: 116,name: "Kankakee Community College",    state: "Illinois",       stateCode: "IL", association: "NJCAA",             conference: "Northern Illinois Junior College Athletic Conference", url: "https://kcc.edu/athletics" },
  { id: 117,name: "Meridian Community College",    state: "Mississippi",    stateCode: "MS", association: "NJCAA",             conference: "Mississippi Association of Community Colleges", url: "https://meridiancc.edu/athletics" },
  { id: 118,name: "Itawamba Community College",    state: "Mississippi",    stateCode: "MS", association: "NJCAA",             conference: "Mississippi Association of Community Colleges", url: "https://iccindians.com" },
  { id: 119,name: "Northeast Mississippi CC",      state: "Mississippi",    stateCode: "MS", association: "NJCAA",             conference: "Mississippi Association of Community Colleges", url: "https://nemcc.edu/athletics" },
  { id: 120,name: "Tyler Junior College",          state: "Texas",          stateCode: "TX", association: "NJCAA",             conference: "Texas Eastern Athletic Conference", url: "https://tjc.edu/athletics" },
  { id: 121,name: "Kilgore College",               state: "Texas",          stateCode: "TX", association: "NJCAA",             conference: "Texas Eastern Athletic Conference", url: "https://kilgore.edu/athletics" },

  // ── NCCAA ────────────────────────────────────────────────────────────────
  { id: 122,name: "Grace College",                 state: "Indiana",        stateCode: "IN", association: "NCCAA",             conference: "NCCAA Midwest Region",             url: "https://gracelandathletics.com" },
  { id: 123,name: "Cedarville University",         state: "Ohio",           stateCode: "OH", association: "NCCAA",             conference: "NCCAA Midwest Region",             url: "https://yellowjackets.cedarville.edu" },
  { id: 124,name: "Mount Vernon Nazarene University", state: "Ohio",        stateCode: "OH", association: "NCCAA",             conference: "NCCAA Midwest Region",             url: "https://mvnucougars.com" },
  { id: 125,name: "Ohio Christian University",     state: "Ohio",           stateCode: "OH", association: "NCCAA",             conference: "NCCAA Midwest Region",             url: "https://athletics.ohiochristian.edu" },
  { id: 126,name: "Roberts Wesleyan University",   state: "New York",       stateCode: "NY", association: "NCCAA",             conference: "NCCAA East Region",                url: "https://athletics.roberts.edu" },
  { id: 127,name: "Nyack College",                 state: "New York",       stateCode: "NY", association: "NCCAA",             conference: "NCCAA East Region",                url: "https://athletics.nyack.edu" },
  { id: 128,name: "North Greenville University",   state: "South Carolina", stateCode: "SC", association: "NCCAA",             conference: "NCCAA South Region",               url: "https://ngu.edu/athletics" },
  { id: 129,name: "Emmanuel College",              state: "Georgia",        stateCode: "GA", association: "NCCAA",             conference: "NCCAA South Region",               url: "https://athletics.ec.edu" },
  { id: 130,name: "Lee University",                state: "Tennessee",      stateCode: "TN", association: "NCCAA",             conference: "NCCAA South Region",               url: "https://leeflames.com" },
  { id: 131,name: "Southwestern Assemblies of God University", state: "Texas", stateCode: "TX", association: "NCCAA",          conference: "NCCAA South Region",               url: "https://saguathletics.com" },
  { id: 132,name: "Crown College",                 state: "Minnesota",      stateCode: "MN", association: "NCCAA",             conference: "NCCAA Central Region",             url: "https://athletics.crown.edu" },
  { id: 133,name: "Northwestern College Minnesota",state: "Minnesota",      stateCode: "MN", association: "NCCAA",             conference: "NCCAA Central Region",             url: "https://athletics.unwsp.edu" },
];

// Pre-computed conference lookup, keyed by association → sorted array of conference names
const CONFERENCES_BY_ASSOCIATION = (() => {
  const map = {};
  for (const school of SCHOOLS) {
    if (!map[school.association]) map[school.association] = new Set();
    map[school.association].add(school.conference);
  }
  for (const key in map) {
    map[key] = [...map[key]].sort();
  }
  return map;
})();
